import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RegisterModal from "@/components/modals/RegisterModal";
import LoginModal from "@/components/modals/LoginModal";
import ToasterProvider from "./providers/ToasterProvider";
import ConnectModal from "@/components/modals/ConnectModal";
import UnconnectModal from "@/components/modals/UnconnectModal";
import AssignMedicationModal from "@/components/modals/MedicationModal";
import CreateEventModal from "@/components/modals/CreateEventModal";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<RegisterModal />
				<LoginModal />
				<ConnectModal />
				<UnconnectModal />
				<AssignMedicationModal />
				<CreateEventModal />
				{children}
				<ToasterProvider />
			</body>
		</html>
	);
}
